### ISSUE TITLE
Correct way to set statsd step interval ?

### ISSUE THREAD

**Issue by laurentperez** [quarkiverse/quarkus-micrometer-registry#39]
Hello, thanks for this extension :)

Quarkus 1.13.1.Final, statsd extension enabled

We're noticing that the default interval is 10 seconds. This can be observed by running `nc -u -l 8125` with quarkusDev, it will print every 10 seconds.

https://github.com/quarkiverse/quarkus-micrometer-registry/blob/main/micrometer-registry-statsd/runtime/src/main/java/io/quarkiverse/micrometer/registry/statsd/StatsdConfig.java refers to a step=1m which does not seem to be working, quarkus.micrometer.export.statsd.step correctly casts as a Duration, if I set "foo" it correctly fails the cast.

However, port works and can be changed. See below where 8125 to 8126 works :

```
quarkus.micrometer.export.statsd.step=1M
quarkus.micrometer.export.statsd.port=8126
```
It's strange that port works fine (integer) but not step (Duration)

Any clues ?

Thanks

**Comment by ebullient** [comment]
The step interval is 1M by default

The polling frequency is 10s by default. The polling frequency "[determines] how often gauges will be polled. When a gauge is polled, its value is recalculated. If the value has changed, it is sent to the StatsD server."

You'll want to adjust the polling frequency, rather than the step interval: "The step size to use in computing windowed statistics like max. The default is 1 minute."

**Comment by laurentperez** [comment]
Thanks !
