### ISSUE TITLE
Minor statsd bug regarding config values

### ISSUE THREAD

**Issue by laurentperez** [quarkiverse/quarkus-micrometer-registry#54]
Hi

Minor bug but it took us a few hours to dig into this and managed to find a workaround

If you use env QUARKUS_MICROMETER_EXPORT_STATSD_* variables to override the quarkus.micrometer.export.statsd.xxx ones, you must define quarkus.micrometer.export.statsd.xxx default ones, otherwise, it will silently not override

For example QUARKUS_MICROMETER_EXPORT_STATSD_HOST will not override unless quarkus.micrometer.export.statsd.host exists (it defaults to 127.0.0.1, but will not be overriden)

I believe this is related to

https://github.com/quarkiverse/quarkus-micrometer-registry/blob/f02291aef45156eda3efd19995461bb3bc0822c1/micrometer-registry-statsd/runtime/src/main/java/io/quarkiverse/micrometer/registry/statsd/StatsdMeterRegistryProvider.java#L29

Simple repro : do not set quarkus.micrometer.export.statsd props, attempt to override with env vars, it will not override

Our fix was to set quarkus.micrometer.export.statsd defaults. Maybe the bootstrap should WARN in logs whenever props are not set in properties.

**Comment by ebullient** [comment]
hmm.

**Comment by ebullient** [comment]
The defaults are defined (in effect), by micrometer itself. They literally do not exist in Quarkus unless you set them. That is somewhat intentional, as I was trying to avoid duplicating the configuration model in quarkus.

captureProperties is going through the general pile of injected quarkus configuration to filter out the set that belong to the registry (a knock-on from the loose property bag). I would have expected the aggregation of sources (including environment variables) to have happened a priori.. such that the config object passed to the provider already has the env vars in it.

**Comment by ebullient** [comment]
In talking w/ @radcortez , this might fix it: https://github.com/smallrye/smallrye-config/pull/563
(which is present in main / 2.x alpha) ..
what version (of quarkus) are you using?

**Comment by laurentperez** [comment]
we're on 1.13.4.Final, we can't bump to jdk11 for quarkus2 yet.

yes the fix might fix this. we'll test this on next 1.x release

**Comment by radcortez** [comment]
I've released a new SR Config version that should be included in Quarkus 1.13.5.Final. It should fix this issue.

**Comment by ebullient** [comment]
@laurentperez any news?
